services:
  # Development services
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: demo
      POSTGRES_PASSWORD: "e8jQejK48O3xx0qYa_7aY8SPmlWs8ScZ"
    volumes:
      - demo_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    ports:
      - "8091:6379"
    command: redis-server --requirepass "nVvHoILG8vaXcMiXkSg04m7JkOsdqC9C"
    environment:
      - REDIS_REPLICATION_MODE=master

  # Test services
  postgres_test:
    image: pgvector/pgvector:pg16
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: demo_test
      POSTGRES_PASSWORD: "GMSzDmupSyll8be1awjjlLJsjIOORhrq"
    volumes:
      - demo_test_data:/var/lib/postgresql/data

  redis_test:
    image: redis:6.2.6
    ports:
      - "9091:6379"
    command: redis-server --requirepass "qhCcZlZHTF-ojUjC5huffF6QwpFpBx6-"
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  demo_data:
  demo_test_data:
